_format_version: "1.1"
services:
  - name: Swagger_Petstore
    protocol: http
    host: localhost
    port: 80
    path: /$%7Bswagger_petstore_url%7D
    plugins: []
    routes:
      - tags:
          &a1
          - OAS3_import
          - OAS3file_petstore_swagger.yaml
        name: Swagger_Petstore-listPets
        methods:
          - GET
        paths:
          - /pets$
        strip_path: false
      - tags: *a1
        name: Swagger_Petstore-createPets
        methods:
          - POST
        paths:
          - /pets$
        strip_path: false
      - tags: *a1
        name: Swagger_Petstore-showPetById
        methods:
          - GET
        paths:
          - /pets/(?<petId>[^/]+)$
        strip_path: false
    tags: *a1
